x-logging: &logging
  driver: json-file
  options:
    max-buffer-size: 4m
    max-file: "5"
    max-size: 10m
    mode: non-blocking
services:
  ccla-scan-app:
    environment:
      - UBIQUBE_ZAP_TOKEN=7da091fe-63a4-48c0-9bfa-7614c49feb7c
    image: ubiqube/cloudclapp-scan:2b4a509e0f85df70d4b8ba738b0c1a11f44a8da7
  ccla-scan-env:
    entrypoint:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.key=7da091fe-63a4-48c0-9bfa-7614c49feb7c
      - -config
      - network.localServers.mainProxy.alpn.enabled=false
      - -config
      - network.localServers.mainProxy.address=0.0.0.0
    image: zaproxy/zap-stable:2.15.0
  cloudclapp:
    depends_on:
      - msa-api
    environment:
      - UBIQUBE_CAPTCHA_SITE_KEY=6Ld2zF4dAAAAAJlqZMIHpPeb3aYhcyy1K3NWPtqi
      - UBIQUBE_LICENSE_AGREEMENT_LINK=https:\/\/cloudclapp.com\/EndUserLicenceAgreement.html
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://localhost:8080
    image: ubiqube/cloudclapp:661f5eda4a6826073021a4b217d2d9ae835478c3
  cloudclapp-wf:
    depends_on:
      - msa-dev
    image: ubiqube/msa2-ccla-wf-installer:sha-2dc5ee70da2245a78ef832ce5bb8b404ac07abc4
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_dev
    volumes:
      - msa_repository:/opt/fmc_repository
      - msa_dev:/opt/devops/
  key-vault:
    cap_add:
      - IPC_LOCK
    command: server
    depends_on:
      - msa-db
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    image: hashicorp/vault:latest
    ports:
      - 8200:8200
    volumes:
      - ./lab/key_vault/config.hcl:/vault/config/config.hcl
  msa-dev:
    command:
      - /docker-entrypoint.sh
      - --cloudclapp
  msa-sms:
    environment:
      - UBIQUBE_INSTALL_AWS_CLI=true
