x-amqp-monitoring: &amqp-monitoring
  AMQP_ADDRESS: core-engine.monitoring
  AMQP_PASSWORD: simetraehcapa
  AMQP_PORT: "5672"
  AMQP_SERVER: msa-broker
  AMQP_USER: artemis
x-amqp-syslog: &amqp-syslog
  AMQP_ADDRESS: core-engine.syslog
  AMQP_PASSWORD: simetraehcapa
  AMQP_PORT: "5672"
  AMQP_SERVER: msa-broker
  AMQP_USER: artemis
x-es-configuration: &es-configuration
  ES_CREDENTIALS: c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=
  ES_SERVERS: msa-es
x-logging: &logging
  driver: json-file
  options:
    max-buffer-size: 4m
    max-file: "5"
    max-size: 10m
    mode: non-blocking
networks:
  default:
    driver_opts:
      encrypted: "true"
services:
  msa-alarm:
    depends_on:
      msa-api:
        condition: service_healthy
      msa-db:
        condition: service_healthy
      msa-es:
        condition: service_started
    environment:
      <<: *es-configuration
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 30s
      test:
        - CMD-SHELL
        - /opt/sms/bin/sms -e ISALIVE -t 1 | grep -q OK || exit 1
      timeout: 5s
    image: ubiqube/msa2-alarm:sha-029276dc72def6b1ea65904e602641da69e2f546
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_alarm
    volumes:
      - msa_sms_logs:/opt/sms/logs
      - msa_alarmbulkfiles:/opt/sms/spool/alarms
      - msa_alarmbulkfiles_err:/opt/sms/spool/alarms-error
  msa-api:
    depends_on:
      msa-db:
        condition: service_healthy
      msa-es:
        condition: service_started
      msa-mongodb:
        condition: service_healthy
    environment:
      <<: *es-configuration
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 90s
      test:
        - CMD-SHELL
        - curl -s --fail http://localhost:8480/actuator/health |jq -r '.status' |grep '^UP$$'
      timeout: 5s
    image: ubiqube/msa2-api:sha-ed25045471205d1f25f2014ec232bfd5d06887b1
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_api
    volumes:
      - msa_entities:/opt/fmc_entities
      - msa_repository:/opt/fmc_repository
      - rrd_repository:/opt/rrd
      - msa_dev:/opt/devops/
      - msa_api_logs:/opt/wildfly/logs
      - msa_api_keystore:/etc/pki/jentreprise
  msa-auth:
    depends_on:
      msa-db:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ubiqube
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 1m
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/8080'
      timeout: 10s
    image: ubiqube/msa2-auth:sha-05d573b53dbb765dd69e0089849c117a43283478
  msa-broker:
    environment:
      ARTEMIS_PASSWORD: simetraehcapa
      ARTEMIS_USER: artemis
      EXTRA_ARGS: --http-host 0.0.0.0 --relax-jolokia --clustered --addresses core-engine.syslog:anycast,core-engine.monitoring:anycast --queues core-engine.syslog:anycast,core-engine.monitoring:anycast
    healthcheck:
      test: ./bin/artemis check node --user=$${ARTEMIS_USER} --password=$${ARTEMIS_PASSWORD} --silent &>/dev/null
    image: docker.io/ubiqube/msa2-broker:sha-c7b473f778eb2cb1d5f5a6496e6064ed0bdec0a8
    logging:
      <<: *logging
    volumes:
      - msa_broker:/var/lib/artemis-instance
  msa-bud:
    depends_on:
      msa-db:
        condition: service_healthy
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 30s
      test:
        - CMD-SHELL
        - /opt/sms/bin/sms -e ISALIVE -t 1 | grep -q OK || exit 1
      timeout: 5s
    image: ubiqube/msa2-bud:sha-8e5656b8c8968e6f6bc8d499a66082cbfb1fea59
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_bud
    volumes:
      - msa_bud_logs:/opt/bud/logs/
  msa-camunda:
    depends_on:
      msa-db:
        condition: service_healthy
    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_PASSWORD: camunda
      DB_URL: jdbc:postgresql://msa-db:5432/process-engine
      DB_USERNAME: camunda
      DB_VALIDATE_ON_BORROW: "true"
      DB_VALIDATION_QUERY: SELECT 1
      WAIT_FOR: msa-db:5432
      WAIT_FOR_TIMEOUT: 60
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 90s
      test:
        - CMD-SHELL
        - curl -s --fail http://localhost:8080/actuator/health |jq -r '.status' |grep '^UP$$'
      timeout: 5s
    image: ubiqube/msa2-camunda:sha-cd2632afdb3be3a38f68cf717347532a61e434e5
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - camunda
  msa-cerebro:
    depends_on:
      msa-es:
        condition: service_started
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa-es:9200
    environment:
      AUTH_TYPE: basic
      BASIC_AUTH_PWD: N@X{M4tfw'5%)+35
      BASIC_AUTH_USER: cerebro
    healthcheck:
      test: curl --fail http://localhost:9000/
    image: ubiqube/msa2-cerebro:sha-a32df159e4cbf22a5fb862239157d0238f496a40
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_cerebro
    ports:
      - 9000:9000
  msa-db:
    environment:
      CAMUNDA_DB: process-engine
      CAMUNDA_PASSWORD: camunda
      CAMUNDA_USER: camunda
      KEY_VAULT_DB: key_vault
      KEY_VAULT_USER: key_vault
      MAX_CONNECTIONS: 1600
      PG_DATABASE: POSTGRESQL
      PG_MODE: primary
      PG_PASSWORD: my_db_password
      PG_PRIMARY_PASSWORD: my_db_password
      PG_PRIMARY_PORT: 5432
      PG_PRIMARY_USER: postgres
      PG_ROOT_PASSWORD: my_db_password
      PG_USER: postgres
    healthcheck:
      interval: 30s
      retries: 5
      test:
        - CMD-SHELL
        - /usr/pgsql-12/bin/pg_isready -h localhost
      timeout: 20s
    image: ubiqube/msa2-db:sha-3ac9bbec183504ebebe37afb00593f00f31734f0
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - db
    shm_size: 1g
    volumes:
      - msa_db:/pgsqldata/pgsql
  msa-dev:
    healthcheck:
      test:
        - CMD-SHELL
        - test -f /usr/bin/install_libraries.sh || echo false
    image: ubiqube/msa2-linuxdev:sha-793fddbbba933bb8b9cd5327581d75e201d976cb
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_dev
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - msa_entities:/opt/fmc_entities
      - msa_repository:/opt/fmc_repository
      - msa_dev:/opt/devops/
  msa-es:
    environment:
      <<: *es-configuration
      ES_JAVA_OPTS: -Xms512m -Xmx1024m
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      script.painless.regex.enabled: "true"
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 30s
      test:
        - CMD-SHELL
        - 'test -f /home/install/init-done && curl -s -XGET -H ''Authorization: Basic c3VwZXJ1c2VyOnheWnl1R002fnU9K2ZZMkc=''  ''http://localhost:9200/_cluster/health?pretty'' | grep -q ''status.*green'' || exit 1'
      timeout: 2s
    image: ubiqube/msa2-es:sha-a8b546208942b3c3057e60494575538678a4968d
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_es
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - msa_es:/usr/share/elasticsearch/data
      - msa_es_config:/usr/share/elasticsearch/config
  msa-front:
    depends_on:
      msa-api:
        condition: service_started
      msa-camunda:
        condition: service_started
      msa-es:
        condition: service_started
      msa-ui:
        condition: service_healthy
    healthcheck:
      test:
        - CMD-SHELL
        - curl -sk --fail https://localhost/msa_version/index.html
    image: ubiqube/msa2-front:sha-7f092c15fda54de453c9c251a14d1690961c04cd
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_front #
    # uncomment one of the 2 sections below when installing a custom certificate
    # - Docker standard standalone installation
    # volumes:
    #    - "msa_front:/etc/nginx/ssl"
    # - Docker Swarm HA installation
    # volumes:
    #    - "/mnt/NASVolume/msa_front:/etc/nginx/ssl"

    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80
      - mode: host
        protocol: tcp
        published: 443
        target: 443
    volumes:
      - msa_front_conf:/etc/nginx/custom_conf.d
  msa-kibana:
    depends_on:
      msa-es:
        condition: service_started
    environment:
      <<: *es-configuration
      ELASTICSEARCH_HOSTS: http://msa-es:9200
      ELASTICSEARCH_URL: http://msa-es:9200
    healthcheck:
      test: curl -k --fail http://localhost:5601/kibana/
    image: ubiqube/msa2-kibana:sha-0a6732f70ec5fc952481763f3762616a64524c80
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_kibana
    ports:
      - 5601:5601
  msa-linux-me:
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - DAC_READ_SEARCH
      - sys_rawio
    devices: # required for dmidecode used by polld/asset
      - /dev/mem:/dev/mem
    hostname: linux-me
    image: ubiqube/msa2-linuxme:sha-abebaa1367d8186067268acb6e4355e107e77e8d
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - linux_me
          - linux-me
    ports:
      - 2224:22
  msa-mongodb:
    env_file:
      - .env
    #      ccla must match user created in mongo-init.js
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-my_db_password}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://${DB_USER:-msaUser}:${DB_PASSWORD:-ubiqube38}@localhost:${DB_PORT:-27017}/${DB_NAME:-msa} --quiet
    image: ubiqube/msa2-mongodb:sha-90b2c29c1e13bc7b82cfadb00cba97ac856fd642
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - msa_mongodb_data:/data/db
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  msa-monitoring:
    depends_on:
      msa-broker:
        condition: service_started
      msa-db:
        condition: service_healthy
      msa-dev:
        condition: service_started
      msa-es:
        condition: service_started
      msa-sms:
        condition: service_started
    environment:
      <<:
        - *es-configuration
        - *amqp-monitoring
      TARGET_MON: RRD
      #   possible values RRD, ES, AMQP
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/sms/bin/sms -e ISALIVE -t 1 | grep -q OK || exit 1
    image: ubiqube/msa2-monitoring:sha-8cc42aa491c598a75d81bf7fbadee07f478dc2ad
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_monitoring
    volumes:
      - msa_dev:/opt/devops/
      - msa_entities:/opt/fmc_entities
      - msa_repository:/opt/fmc_repository
      - rrd_repository:/opt/rrd
      - msa_sms_logs:/opt/sms/logs
      - msa_monitbulkfiles:/opt/sms/spool/parser
      - msa_monitbulkfiles_err:/opt/sms/spool/parser-error
  msa-parse:
    depends_on:
      msa-broker:
        condition: service_started
      msa-db:
        condition: service_healthy
      msa-dev:
        condition: service_started
      msa-es:
        condition: service_started
      msa-sms:
        condition: service_healthy
    environment:
      <<:
        - *es-configuration
        - *amqp-syslog
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/sms/bin/sms -e ISALIVE -t 1 | grep -q OK || exit 1
    image: ubiqube/msa2-parse:sha-9beb01d1f84dd085e347cb9714dbcaddad791974
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_parse
    volumes:
      - msa_dev:/opt/devops/
      - msa_parsebulkfiles:/opt/sms/spool/parser
      - msa_parsebulkfiles_err:/opt/sms/spool/parser-error
  msa-rsyslog:
    depends_on:
      msa-broker:
        condition: service_started
    environment:
      <<: *amqp-syslog
      ACTIONTYPE: omamqp1
    healthcheck:
      test:
        - CMD-SHELL
        - ps -p 1 -h -o%cpu | awk '{if ($$1 > 99) exit 1; else exit 0;}'
    image: ubiqube/msa2-rsyslog:sha-4df2a98238333312b88cf4ad96167e64f1937d00
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_rsyslog
    ports:
      - mode: host
        protocol: udp
        published: 514
        target: 514
      - mode: host
        protocol: tcp
        published: 514
        target: 514
      - mode: host
        protocol: tcp
        published: 6514
        target: 6514
  msa-sms:
    depends_on:
      msa-db:
        condition: service_healthy
      msa-dev:
        condition: service_started
      msa-es:
        condition: service_started
    environment:
      <<: *es-configuration
    healthcheck:
      interval: 10s
      retries: 10
      start_period: 30s
      test:
        - CMD-SHELL
        - /opt/sms/bin/sms -e ISALIVE -t 1 | grep -q OK || exit 1
      timeout: 5s
    image: ubiqube/msa2-sms:sha-eaf48e66d7a86cfc4a26079033bccce09a90e362
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_sms
    ports:
      - mode: host
        protocol: udp
        published: 69
        target: 69
      - mode: host
        protocol: udp
        published: 5200
        target: 5200
    volumes:
      - msa_dev:/opt/devops/
      - msa_entities:/opt/fmc_entities
      - msa_repository:/opt/fmc_repository
      - msa_sms_logs:/opt/sms/logs
      - msa_svn:/opt/svnroot
      - msa_svn_ws:/opt/sms/spool/routerconfigs
      - msa_bulkfiles:/opt/sms/spool/parser
      - msa_bulkfiles_err:/opt/sms/spool/parser-error
  msa-smtp:
    environment:
      ALLOWED_SENDER_DOMAINS: ""
      ALLOW_EMPTY_SENDER_DOMAINS: "true"
      HOSTNAME: msa-smtp
      # RELAYHOST: <MTA ip>:25
      POSTFIX_message_size_limit: 2097152
    image: boky/postfix:4.2.1-alpine
  msa-snmptrap:
    depends_on:
      msa-db:
        condition: service_healthy
      msa-dev:
        condition: service_started
      msa-es:
        condition: service_started
    environment:
      <<: *es-configuration
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/sms/bin/sms -e ISALIVE -t 1 | grep -q OK || exit 1
    image: ubiqube/msa2-snmptrap:sha-942e1c4b7a65648ee8d28b4424fd3e3fdee6f8d5
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_snmptrap
    ports:
      - mode: host
        protocol: udp
        published: 162
        target: 162
    volumes:
      - msa_dev:/opt/devops/
      - msa_repository:/opt/fmc_repository
      - msa_snmptrapbulkfiles:/opt/sms/spool/parser
      - msa_snmptrapbulkfiles_err:/opt/sms/spool/parser-error
  msa-ui:
    depends_on:
      msa-api:
        condition: service_started
    environment:
      - FEATURE_ADMIN=true
      - FEATURE_REPOSITORY=true
      - FEATURE_CONNECTION_STATUS=true
      - FEATURE_ALARMS=true
      - FEATURE_LICENCE=true
      - FEATURE_TOPOLOGY=true
      - FEATURE_MONITORING_PROFILES=true
      - FEATURE_PROFILE_AUDIT_LOGS=true
      - FEATURE_PERMISSION_PROFILES=true
      - FEATURE_AI_ML=false
      - FEATURE_MICROSERVICE_BULK_OPERATION=false
      - FEATURE_EDIT_VARIABLES_IN_MICROSERVICE_CONSOLE=true
      - FEATURE_WORKFLOW_OWNER=false
      - FEATURE_PERMISSION_PROFILE_LABELS=false
      - FEATURE_BPM=true
      - UBIQUBE_ES_SECURITY_DISABLED=true
      - FEATURE_ALARMS_AUTO_CLEARANCE=false
      - FEATURE_IMPORT_WITH_SAME_AND_UPPERRANK=true
      - FEATURE_REPOFOLDERLIST=[\"Datafiles\", \"Shared\"]
      - FEATURE_ALARM_TROUBLE_TICKET=false
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://localhost:8080
    image: ubiqube/msa2-ui:669887eed0c4047faac9e9d120ad3e147055eb7b
    logging:
      <<: *logging
    networks:
      default:
        aliases:
          - msa_ui
  msa2-es-ilm:
    container_name: msa2_es-ilm
    # healthcheck:
    #  test: ["CMD-SHELL", "find /opt/msa2-es-ilm/log/log_retention.log -type f -mmin -10"]
    depends_on:
      msa-es:
        condition: service_started
    environment:
      <<: *es-configuration
      ELASTICSEARCH_URL: msa_es:9200
      UBI_ES_ALARM_INDEX_MULTIPLE_TTL: '*|90d'
      UBI_ES_AUDIT_INDEX_MULTIPLE_TTL: '*|90d'
      UBI_ES_CACHE_INDEX_DEFAULT_TTL: 1w
      UBI_ES_DELETE_SCROLL_SIZE: "4000"
      UBI_ES_ILM_LOG_CRONTAB: '# */2 * * * * root php /opt/ubi-es-ilm/log_retention_management.php --verbose=3 > /proc/1/fd/1 2>&1'
      # For elasticsearch scripts /opt/ubi-es-ilm/log_retention_management.php
      # UBI_ES_INDEX_MULTIPLE_TTL:        "type:traffic|7d,type:event|30d,*|90d"
      UBI_ES_INDEX_MULTIPLE_TTL: '*|90d'
      UBI_ES_LOG_DETENTION_DELETE: "true"
      UBI_ES_LOG_SEARCH_INDEX_LIST: ubilogs
      UBI_ES_MAX_DOCS: ""
      UBI_ES_RETENTION_ALARM_INDEX_NAME: ubialarm*
      UBI_ES_RETENTION_AUDIT_INDEX_NAME: ubiaudit*
      UBI_ES_RETENTION_INDEX_NAME: ubilogs*
    image: ubiqube/msa2-es-ilm:sha-6071ae10ede7a06b1982210b7da962ac862586bb
    networks:
      default:
        aliases:
          - msa2_es-ilm
    restart: unless-stopped
    volumes:
      - msa2_es-ilm:/opt/msa2-es-ilm
volumes:
  msa2_es-ilm:
  msa_ai_ml_db:
  msa_alarmbulkfiles:
  msa_alarmbulkfiles_err:
  msa_api_keystore:
  msa_api_logs:
  msa_broker:
  msa_bud_logs:
  msa_bulkfiles:
  msa_bulkfiles_err:
  msa_db:
  msa_dev:
  msa_entities:
  msa_es:
  msa_es_config:
  msa_front:
  msa_front_conf:
  msa_mongodb_data:
  msa_monitbulkfiles:
  msa_monitbulkfiles_err:
  msa_parsebulkfiles:
  msa_parsebulkfiles_err:
  msa_repository:
  msa_sms_logs:
  msa_snmptrapbulkfiles:
  msa_snmptrapbulkfiles_err:
  msa_svn:
  msa_svn_ws:
  rrd_repository:
  rsyslog_conf:
