x-logging: &logging
  driver: json-file
  options:
    max-buffer-size: 4m
    max-file: "5"
    max-size: 10m
    mode: non-blocking
x-placement_app: &placement_app
  placement:
    constraints:
      - node.labels.worker==app
    max_replicas_per_node: 1
  replicas: 1
configs:
  nginx_ccla.conf:
    file: ./front/nginx_ccla.conf
services:
  ccla-scan-app:
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: 1
    environment:
      - UBIQUBE_ZAP_TOKEN=7da091fe-63a4-48c0-9bfa-7614c49feb7c
    image: ubiqube/cloudclapp-scan:2b4a509e0f85df70d4b8ba738b0c1a11f44a8da7
  ccla-scan-env:
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: 1
    entrypoint:
      - zap.sh
      - -daemon
      - -host
      - 0.0.0.0
      - -config
      - api.addrs.addr.name=.*
      - -config
      - api.addrs.addr.regex=true
      - -config
      - api.key=7da091fe-63a4-48c0-9bfa-7614c49feb7c
    image: zaproxy/zap-stable:2.15.0
  cloudclapp:
    depends_on:
      - msa-api
    deploy:
      placement:
        max_replicas_per_node: 1
      replicas: 1
    environment:
      - UBIQUBE_CAPTCHA_SITE_KEY=6Ld2zF4dAAAAAJlqZMIHpPeb3aYhcyy1K3NWPtqi
      - UBIQUBE_LICENSE_AGREEMENT_LINK=https:\/\/cloudclapp.com\/EndUserLicenceAgreement.html
    #profiles: ["ccla"]
    healthcheck:
      test:
        - CMD-SHELL
        - curl --fail http://localhost:8080
    image: ubiqube/cloudclapp:de66eeec8fe037062997347ef80677e146825bd0
  cloudclapp-wf:
    depends_on:
      - msa-dev
    deploy:
      <<: *placement_app
    image: ubiqube/msa2-ccla-wf-installer:sha-132e010a6017fff483cbbcf6dc04c49a008fb55a
    logging:
      <<: *logging
    volumes:
      - /mnt/NASVolume/msa_repository:/opt/fmc_repository
      - /mnt/NASVolume/msa_dev:/opt/devops/
  key-vault:
    cap_add:
      - IPC_LOCK
    command: server
    depends_on:
      - msa-db
    deploy:
      placement:
        constraints:
          - node.role==manager
        max_replicas_per_node: 1
      replicas: 1
    environment:
      VAULT_ADDR: http://0.0.0.0:8200
    image: hashicorp/vault:latest
    ports:
      - 8200:8200
    volumes:
      - ./lab/key_vault/config.hcl:/vault/config/config.hcl
  msa-dev:
    command:
      - /docker-entrypoint.sh
      - --cloudclapp
  msa-front:
    configs:
      - source: nginx_ccla.conf
        target: /etc/nginx/custom_conf.d/https/nginx_ccla.conf
  msa-sms:
    environment:
      - UBIQUBE_INSTALL_AWS_CLI=true
