= Quickstart

This quickstart method will get you started with the MSActivator(TM) (MSA), which is a next generation Integrated Automation Platform. By following this quickstart you will be able to test out the full capabilities of the MSA with a limited license.

Empower your business by automating all manner of business processes through tight integration of every entity in your digital landscape.

== Prerequisites

Before starting this tutorial, first install link:https://docs.docker.com/install/[Docker] on your machine. 
Next install link:https://docs.docker.com/compose/install/[Docker Compose] on your machine.

== Installing the application

The easiest way to get started with the MSA is to follow this quickstart guide.

This quickstart guide will setup a mini-lab composed of the MSA-2 containers as well as a Linux container that you can use for your tests. (see below for mode details)


1. check your dockerhub account password - or create a new account
2. ask for access to private repo: `ubiqube/msa2`
3. check your docker engine has access to dockerhub
4. clone this repo: `git clone https://github.com/ubiqube/quickstart.git`
5. `cd quickstart`
6. run: `docker login`
7. run: `docker-compose up -d`
8. browse: https://localhost/ and connect as username `ncroot`, password `ubiqube`

NOTE: It might take approximately five minutes after connecting to https://localhost/ to be able to login.
NOTE: There might be a pop-up warning of a self-signed cert that needs to be accepted to proceed.

Docker Compose will set up MSA as well as one virtual machine such as a Linux Centos 6.8 container on which to experiment (this container is defined in lab/linux.me/Dockerfile in this QuickStart repository).  

When Docker Compose is done deploying and the MSA platform is running, you will be able to open the dashboard at link:https://127.0.0.1[]. 

When you see the following output, the MSA platform is ready to be used

```
Creating quickstart_ui_1      ... done
Creating quickstart_db_1      ... done
Creating quickstart_es_1      ... done
Creating quickstart_me_1      ... done
Creating quickstart_camunda_1 ... done
Creating quickstart_kibana_1  ... done
Creating quickstart_api_1     ... done
Creating quickstart_front_1   ... done
```

If you get a gateway error, the web server is probably still starting and you may have to wait for 10-20 more seconds before trying again.

To get an interactive shell on the MSA main container (this will be needed later).
```
docker-compose exec api bash
```
You can start working with the MSA and create tenants, customers and managed entities manually.
You can also choose to run the script `create_tenant_customer.sh` to automatically create a test environement.

```
docker-compose exec api /usr/bin/create_tenant_customer.sh
```
== Breaking Down/Resetting the Quickstart Environment
To fully clean up or reset the environment, run the following commands:

1. `docker-compose down`
2. `docker volume prune -f`
3. `docker ps -a | grep "ubiqube" | awk '{print $3}' | xargs docker rmi`
4. `docker images | grep "ubiqube" | awk '{print $3}' | xargs docker rmi`

This will give you a clean environment next time you run `docker-compose up`.

NOTE: To get the access to the UBiqube dockerhub private repository, please contact us at info@ubiqube.com.

== Requirements on the host machine

The host machine should have hardware specs similar to that
of the VM running the .ova flavour of MSA:

.on a PC
- minimum 8GB memory, 2CPU, 100GB space

.on a production environment 
- minimum 16GB memory, 4CPU, 100GB space


=== Docker for Linux (or Linux VM)
----
sudo sysctl -w vm.max_map_count=262144
sudo tee -a /etc/sysctl.conf <<< "vm.max_map_count=262144"
----

=== Docker for Mac

From the command line, run:
----
screen ~/Library/Containers/com.docker.docker/Data/vms/0/tty
----	
Press enter and use `sysctl` to configure vm.max_map_count:
----
sysctl -w vm.max_map_count=262144
----	
To exit the screen session, type Ctrl a d.

=== Docker for Windows
----
docker-machine create -d virtualbox  \
	--virtualbox-cpu-count=2 \
	--virtualbox-memory=8192 \
	--virtualbox-disk-size=50000 \
	default
----

In the docker VM, do as for Linux host above:
----
sudo sysctl -w vm.max_map_count=262144
sudo tee -a /etc/sysctl.conf <<< "vm.max_map_count=262144"
----

The docker VM is mapped to a local IP on the Windows host,
access to the msa is _NOT_ done via `https://localhost`,
you must lookup the IP with:

```
$ docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER     ERRORS
default   *        virtualbox   Running   tcp://192.168.99.100:2376           v19.03.5
```

The quickstart method will give you the ability to run a 'lab in a box' locally.  This will allow you to test out a true Integrated Automation Platform, such as the next generation MSActivator(TM).

The license on this is a trial which will allow a limited number of entities (or devices) to be connected and will expire in 30 days.

For further information, please contact UBiqube at info@ubiqube.com .

