#!/bin/bash
IMAGE_NAME="$1"
IMAGE_TAG="$2"

sed -i "s,$IMAGE_NAME:.\+$,$IMAGE_NAME:$IMAGE_TAG," docker-compose.yml
sed -i "s,$IMAGE_NAME:.\+$,$IMAGE_NAME:$IMAGE_TAG," docker-compose.e2e.yml
sed -i "s,$IMAGE_NAME:.\+$,$IMAGE_NAME:$IMAGE_TAG," docker-compose.ha.yml
sed -i "s,$IMAGE_NAME:.\+$,$IMAGE_NAME:$IMAGE_TAG," docker-compose.ccla.yml
sed -i "s,$IMAGE_NAME:.\+$,$IMAGE_NAME:$IMAGE_TAG," docker-compose.ccla.ha.yml
sed -i "s,$IMAGE_NAME:.\+$,$IMAGE_NAME:$IMAGE_TAG," docker-compose.mariadb.yml
